version: '3.7'

services:
  transaction_api:
    container_name: transaction_api
    env_file:
      - ../cmd/transaction-service/.env
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - transaction_service_mysql

  transaction_service_mysql:
    container_name: transaction_service_mysql
    image: mysql:8.4.0
    volumes:
      - ../scripts/sql/:/docker-entrypoint-initdb.d/
      - transaction_service_mysql_data:/var/lib/mysql
    env_file:
      - ../cmd/transaction-service/.env
    ports:
      - "3306:3306"
    expose:
      - 3306
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    env_file:
      - ../cmd/transaction-service/.env
    depends_on:
      - transaction_service_mysql

volumes:
  transaction_service_mysql_data:
    driver: "local"